version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "wukong-engine"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
